lista = [45, 32, 3, 78]
print("lista original: ", lista)
lista.append(995)
lista.append(7)
print("lista después de usar append: ", lista)
lista.sort()
print("lista ordenada: ", lista)
lista.reverse()
print("lista al revés: ", lista)
listaextend = (1, 5, 87, 45)
lista.extend(listaextend)
print("lista después del extend: ", lista)
lista.sort(reverse=True)
print("lista ordenada al revés: ", lista)
print("Número de elementos 45: ", lista.count(45))
lista.insert(4, 111)
print("lista después de insert: ", lista)
lista.remove(45)
print("lista después de remove: ", lista)
print("posición del elemento 111: ", lista.index(111))
lista.pop()
print("lista después de pop: ", lista)
lista.clear()
print("lista después de clear: ", lista)